# Generated by Django 4.2.4 on 2023-08-12 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invitio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="g_id",
            new_name="g_p_id",
        ),
    ]
